import Head from "next/head";

import { LinkButton } from "@/components";

import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Review Charter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.home}>
        <div className={styles["home__container"]}>
          <h1 className={styles["home__title"]}>Review Charter</h1>
          <p className={styles["home__description"]}>
            Visualise
            <a
              className={styles["home__description-link"]}
              href="https://anilist.co"
            >
              AniList
            </a>
            data in multiple charts.
          </p>
          <div className={styles["home__button-container"]}>
            <LinkButton href="/user" text="Chart a User" />
          </div>
        </div>
      </main>
    </>
  );
}
